CREATE TABLE public.infor_users
(
    id         serial4      NOT NULL,
    first_name varchar(255) NULL,
    mid_name   varchar(255) NULL,
    last_name  varchar(255) NULL,
    CONSTRAINT infor_users_pkey PRIMARY KEY (id)
);

ALTER TABLE INFOR_USERS
    ALTER COLUMN first_name SET NOT NULL;
ALTER TABLE INFOR_USERS
    ALTER COLUMN last_Name set NOT NULL;
----------------------------------------------------------------------------
CREATE TABLE public.users
(
    user_id         serial4      NOT NULL,
    email           varchar(255) NULL,
    "password"      varchar(60)  NULL,
    pass_updated_at timestamp(0) NULL,
    last_login_at   timestamp(0) NULL,
    failed_at       timestamp(0) NULL,
    failed_count    numeric(3)   NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
    --CONSTRAINT fk_user_infor FOREIGN KEY (user_id) REFERENCES public.infor_users(id)
);

ALTER TABLE USERS
    ALTER COLUMN email set NOT NULL;
ALTER TABLE USERS
    ALTER COLUMN password set NOT NULL;
ALTER TABLE USERS
    ALTER COLUMN failed_Count set NOT NULL;

ALTER TABLE USERS
    ADD CONSTRAINT FK_user_infor FOREIGN KEY (user_Id) REFERENCES INFOR_USERS (id);


---- alter table users ALTER COLUMN userId  generated by default as identity;   // disable indetity 


--commit work;
----------------------------------------------------------------------------

CREATE TABLE LOCATIONS
(
    location_Id     SERIAL PRIMARY KEY,
    location_Code   varchar(32),
    location_Status numeric(3, 0),
    created_By      numeric(10, 0),
    updated_By      numeric(10, 0),
    created_At      timestamp(0),
    updated_At      timestamp(0),
    location_Name   varchar(255),
    location_Des    varchar(255)
    --CONSTRAINT PK_location PRIMARY KEY (location_Id)
);

---  alter table LOCATIONS ALTER COLUMN locationId  generated  always as identity ;

ALTER TABLE LOCATIONS
    ALTER COLUMN location_Name set NOT NULL;
ALTER TABLE LOCATIONS
    ALTER COLUMN location_Code set NOT NULL;
ALTER TABLE LOCATIONS
    ALTER COLUMN location_Status set NOT NULL;
ALTER TABLE LOCATIONS
    ALTER COLUMN created_By set NOT NULL;
ALTER TABLE LOCATIONS
    ALTER COLUMN updated_By set NOT NULL;
ALTER TABLE LOCATIONS
    ALTER COLUMN created_At set NOT NULL;
ALTER TABLE LOCATIONS
    ALTER COLUMN updated_At set NOT NULL;

----------------------------------------------------------------------------

CREATE TABLE USERS_LOCATIONS
(
    id          SERIAL PRIMARY KEY,
    user_Id     SERIAL,
    location_Id SERIAL,
    role        numeric(3, 0),
    --CONSTRAINT PK_users_locations PRIMARY KEY (id),
    CONSTRAINT FK_location FOREIGN KEY (location_Id) REFERENCES LOCATIONS (location_Id),
    CONSTRAINT FK_user FOREIGN KEY (user_Id) REFERENCES USERS (user_Id)
);


ALTER TABLE USERS_LOCATIONS
    ALTER COLUMN user_Id set NOT NULL;
ALTER TABLE USERS_LOCATIONS
    ALTER COLUMN role set NOT NULL;

---- ALTER TABLE USERS_LOCATIONS  ALTER COLUMN (USERID NOT NULL)


----------------------------------------------------------------------------
CREATE TABLE BRANDS
(
    id          SERIAL PRIMARY KEY,
    location_Id SERIAL,
    created_By  integer,
    updated_By  integer,
    created_At  timestamp(0),
    updated_At  timestamp(0),
    brand_Name  varchar(255),
    brand_Des   varchar(255),
    brand_Est   numeric(5, 0),
-- CONSTRAINT PK_brand PRIMARY KEY (id),
    CONSTRAINT FK_brand_user FOREIGN KEY (location_Id) REFERENCES LOCATIONS (location_Id),
    CONSTRAINT FK_brand_createBy FOREIGN KEY (created_By) REFERENCES INFOR_USERS (id),
    CONSTRAINT FK_brand_updateBy FOREIGN KEY (updated_By) REFERENCES INFOR_USERS (id)
);


ALTER TABLE BRANDS
    ALTER COLUMN location_Id set NOT NULL;
ALTER TABLE BRANDS
    ALTER COLUMN created_By set NOT NULL;
ALTER TABLE BRANDS
    ALTER COLUMN created_At set NOT NULL;
ALTER TABLE BRANDS
    ALTER COLUMN updated_At set NOT NULL;
ALTER TABLE BRANDS
    ALTER COLUMN brand_Name set NOT NULL;
ALTER TABLE BRANDS
    ALTER COLUMN brand_Est set NOT NULL;











